### ISSUE TITLE
Review of Project 02 by Qinhui

### ISSUE THREAD

**Issue by xqh0104** [mwiener09/istm-6212#3]
Hi Marissa,

You did a great job on completing your second project. I downloaded your code, and I can smoothly run the code on datanotebook.org.
Also, your annotation is really clear. Though my topic is not about crime, I can still understand what is the content of crime dataset.
## First and Second Question
For the first and second question, basically we use same way to explore the data.
## Third Question
For the third question,  I like the way you handle data. Defining a new field to distinguish the crime makes the data easier to read. And I noticed that you make a combination of file_number and file_number_event to be a unique ID. This is really nice. When I tried to create a new dimension table, I just create a new column and set it serial.
## Fourth Question
For the fourth question, you explained clearly what you want to find using SQL query. And I am impressed by the case expression you use in query. I learned from that.
Finally, you gave out suggestion based on your analysis in question4, which is logical and makes the homework meaningful.
## Bonus
For the bonus part, I like timestamp part you mentioned. What you explained for automation is logical and clear. I learn a lot from this part.

Thank you,
Qinhui

**Comment by mwiener09** [comment]
Thanks Qinhui!
