### ISSUE TITLE
Project 2 Review by Amit

### ISSUE THREAD

**Issue by atalapatra** [mwiener09/istm-6212#4]
Hi Marissa,

Great job on the project. Here’s my review:

Part 1
The data exploration was very thorough and clearly organized. I like that you listed the questions that you were interested in exploring.

Part 2
I liked your use of a table showing column data types, max lengths, and whether fields are nullable. This layout, and the rest of your data exploration made the contents of the data in your database very clear to me.

Part 3
The schema layout made sense and the creation of the dimension tables was explained well.

Part 4
I learned a lot from the SQL statements you used to create concise bar plots. I was having difficulty with this in my own project, so I’ll refer to some of your examples here in the future to create better outputs.

Extra Credit
I like the level of detail you went into to answer each of these questions, and the answers made sense to me.

**Comment by mwiener09** [comment]
Thanks Amit!
